### PR TITLE
Add base56 vectors

### PR DESCRIPTION
**Pull request by alexhauser**
Add additional vectors for testing the base56 encoding used to create textual versions of binary identity data.

**Still needs independent verification!**

### CODE REVIEW

**Comment by alexhauser** [comment]
Meanwhile, my vectors were fully confirmed by Paul Holder on the forums (see https://sqrl.grc.com/threads/test-vectors.1035/post-8646) and one sample was confirmed by Paul Farrer using his SqrlVect tool (https://sqrl.grc.com/threads/test-vectors.1035/post-8636). 

I guess we can be pretty confident at this point that the vectors are ok.

Since we now have 2 base56 vectors with the same name, I suggest to rename mine to `base56-full-vectors.txt` or similar.

**Comment by shanedk** [comment]
I was thinking something like `full-format` or something. I do think there's room for both our sets of vectors, mine for more preliminary testing and yours for full format. Just one thought: Do you think fully formatted vectors should include spaces and line breaks?

**Comment by alexhauser** [comment]
>I was thinking something like full-format or something.

Perfect!

>Do you think fully formatted vectors should include spaces and line breaks?

Matter of taste, I think. For me, formatting has nothing to do with the core functionality. My base56 functions produce unformatted output, and I have a separate function to deal with the formatting, which gives me maximum flexibility.

The way it is now, I don't have to encode the bas5e6 result once more with base64_url or hex, which I like.

**Comment by shanedk** [comment]
I wasn't thinking that. I was just thinking of including spaces and newlines (using `\n`) in the CSV.

**Comment by alexhauser** [comment]
>I was just thinking of including spaces and newlines (using \n) in the CSV.

That's what I'm referring to when I say "formatting". To me, it's unnecessary cruft. But you're the maintainer, and I'm gladly putting it in if you want me to. 😊

**Comment by alexhauser** [comment]
Shane, I'll close this PR and create a new one with the discussed changes (rename to `base56-full-format-vectors.txt`, adding an all-null-bytes vector and formatting).

(I can't update this one because I needed to remove and recreate my fork in the meantime because I messed up my git environment)

**Pull request closed without merging**
